mod continue_break;
mod copy_payload;
mod counted_loop;
mod exit_flag_default;
mod exit_flag_loop;
mod for_each_val;
mod guard_block_breaks;
mod guard_break_unreachable;
mod guard_early_return;
mod ir_label_cleanup;
mod label_block_collapse;
mod label_block_tail_guard;
mod label_block_to_loop;
mod label_guard_if;
mod label_if_chain;
mod label_ladder_inline;
mod label_ladder_match;
mod label_ladder_reduce;
mod linear_memory_vec_build;
mod loop_break_tail_return;
mod loop_guard_if;
mod loop_if_break_else;
mod loop_if_unreachable;
mod loop_no_control;
mod loop_to_while;
mod loop_unreachable;
mod next_string_while;
mod function_signature;
mod read_price_data;
mod simple_loop_unlabel;
mod single_pass_loop;
mod single_pass_unlabeled_loop;
mod unwrap_if_else;

pub use continue_break::ContinueBreakCleanup;
pub use copy_payload::CopyPayloadPattern;
pub use counted_loop::CountedLoopPattern;
pub use exit_flag_default::ExitFlagDefaultAssign;
pub use exit_flag_loop::ExitFlagLoopCollapse;
pub use for_each_val::ForEachValPattern;
pub use guard_block_breaks::GuardBlockBreaks;
pub use guard_break_unreachable::GuardBreakUnreachablePattern;
pub use ir_label_cleanup::IrLabelCleanup;
pub use label_block_collapse::LabelBlockCollapse;
pub use label_block_tail_guard::LabelBlockTailGuard;
pub use label_block_to_loop::LabelBlockToLoop;
pub use label_guard_if::LabelGuardIf;
pub use label_if_chain::LabelIfChain;
pub use label_ladder_inline::LabelLadderInline;
pub use label_ladder_match::LabelLadderMatch;
pub use label_ladder_reduce::LabelLadderReduce;
pub use linear_memory_vec_build::LinearMemoryVecBuildPattern;
pub use loop_guard_if::LoopGuardToIf;
pub use loop_if_unreachable::LoopIfUnreachableToBlock;
pub use loop_to_while::LoopToWhile;
pub use loop_unreachable::LoopUnreachableElse;
pub use next_string_while::NextStringWhile;
pub use function_signature::FunctionSignaturePattern;
pub use read_price_data::ReadPriceDataPattern;
pub use simple_loop_unlabel::SimpleLoopUnlabel;
pub use single_pass_loop::SinglePassLoopCleanup;
pub use single_pass_unlabeled_loop::SinglePassUnlabeledLoopCleanup;

mod consolidate_comments;
mod conversion_elimination;
mod deduplicate_variables;
mod initial_assignment;
mod math_operations;
mod missing_semicolons;
mod smart_variable_naming;
mod stack_copy_vec_return;
mod stack_frame;
mod storage_access;
mod undefined_helpers;
mod variable_naming;

pub use consolidate_comments::ConsolidateCommentsPattern;
pub use conversion_elimination::ConversionEliminationPattern;
pub use deduplicate_variables::DeduplicateVariablesPattern;
pub use guard_early_return::GuardEarlyReturn;
pub use initial_assignment::InitialAssignmentPattern;
pub use loop_break_tail_return::LoopBreakTailReturn;
pub use loop_if_break_else::LoopIfBreakElse;
pub use loop_no_control::LoopNoControlToBlock;
pub use math_operations::MathOperationsPattern;
pub use missing_semicolons::MissingSemicolonsPattern;
pub use smart_variable_naming::SmartVariableNamingPattern;
pub use stack_copy_vec_return::StackCopyVecReturnPattern;
pub use stack_frame::StackFramePattern;
pub use storage_access::StorageAccessPattern;
pub use undefined_helpers::UndefinedHelpersPattern;
pub use unwrap_if_else::UnwrapIfElseBlock;
pub use variable_naming::VariableNamingPattern;
