mod continue_break;
mod assert_condition_cleanup;
mod break_to_label;
mod copy_payload;
mod constant_match_cleanup;
mod counted_loop;
mod else_compaction;
mod empty_if_block;
mod exit_flag_default;
mod exit_flag_loop;
mod for_each_val;
mod guard_block_breaks;
mod guard_break_unreachable;
mod guard_early_return;
mod guard_unreachable_assert;
mod if_condition_cleanup;
mod if_chain_to_guards;
mod inline_frame_base;
mod ir_label_cleanup;
mod label_block_collapse;
mod label_block_tail_guard;
mod label_block_to_loop;
mod label_guard_if;
mod label_if_chain;
mod label_ladder_inline;
mod label_ladder_match;
mod label_ladder_reduce;
mod label_match_break_guard;
mod label_trap_tail_inline;
mod linear_memory_vec_build;
mod loop_break_tail_return;
mod loop_guard_chain_to_if;
mod loop_guard_if;
mod loop_if_break_else;
mod loop_if_unreachable;
mod loop_no_control;
mod loop_to_while;
mod loop_trap_tail_guard;
mod loop_unreachable;
mod loop_without_control_to_block;
mod next_string_while;
mod function_signature;
mod redundant_type_check;
mod redundant_scope;
mod return_void_cleanup;
mod remove_unused_locals;
mod remove_terminal_return;
mod simple_loop_unlabel;
mod single_pass_loop;
mod single_pass_unlabeled_loop;
mod prune_empty_if_blocks;
mod terminal_scope_unwrap;
mod unwrap_if_else;

pub use continue_break::ContinueBreakCleanup;
pub use assert_condition_cleanup::AssertConditionCleanupPattern;
pub use break_to_label::BreakToLabelPattern;
pub use copy_payload::CopyPayloadPattern;
pub use constant_match_cleanup::ConstantMatchCleanupPattern;
pub use counted_loop::CountedLoopPattern;
pub use else_compaction::ElseCompactionPattern;
pub use empty_if_block::EmptyIfBlockPattern;
pub use exit_flag_default::ExitFlagDefaultAssign;
pub use exit_flag_loop::ExitFlagLoopCollapse;
pub use for_each_val::ForEachValPattern;
pub use guard_block_breaks::GuardBlockBreaks;
pub use guard_break_unreachable::GuardBreakUnreachablePattern;
pub use if_condition_cleanup::IfConditionCleanupPattern;
pub use if_chain_to_guards::IfChainToGuardsPattern;
pub use inline_frame_base::InlineFrameBasePattern;
pub use guard_unreachable_assert::GuardUnreachableAssertPattern;
pub use ir_label_cleanup::IrLabelCleanup;
pub use label_block_collapse::LabelBlockCollapse;
pub use label_block_tail_guard::LabelBlockTailGuard;
pub use label_block_to_loop::LabelBlockToLoop;
pub use label_guard_if::LabelGuardIf;
pub use label_if_chain::LabelIfChain;
pub use label_ladder_inline::LabelLadderInline;
pub use label_ladder_match::LabelLadderMatch;
pub use label_ladder_reduce::LabelLadderReduce;
pub use label_match_break_guard::LabelMatchBreakGuard;
pub use label_trap_tail_inline::LabelTrapTailInlinePattern;
pub use linear_memory_vec_build::LinearMemoryVecBuildPattern;
pub use loop_guard_if::LoopGuardToIf;
pub use loop_guard_chain_to_if::LoopGuardChainToIf;
pub use loop_if_unreachable::LoopIfUnreachableToBlock;
pub use loop_to_while::LoopToWhile;
pub use loop_trap_tail_guard::LoopTrapTailGuardPattern;
pub use loop_unreachable::LoopUnreachableElse;
pub use loop_without_control_to_block::LoopWithoutControlToBlockPattern;
pub use next_string_while::NextStringWhile;
pub use function_signature::FunctionSignaturePattern;
pub use redundant_scope::RedundantScopePattern;
pub use redundant_type_check::RedundantTypeCheckPattern;
pub use return_void_cleanup::ReturnVoidCleanupPattern;
pub use remove_unused_locals::RemoveUnusedLocalsPattern;
pub use remove_terminal_return::RemoveTerminalReturnPattern;
pub use simple_loop_unlabel::SimpleLoopUnlabel;
pub use single_pass_loop::SinglePassLoopCleanup;
pub use single_pass_unlabeled_loop::SinglePassUnlabeledLoopCleanup;
pub use prune_empty_if_blocks::PruneEmptyIfBlocksPattern;
pub use terminal_scope_unwrap::TerminalScopeUnwrapPattern;

mod consolidate_comments;
mod conversion_elimination;
mod deduplicate_variables;
mod dead_temp_cleanup;
mod initial_assignment;
mod inline_val_roundtrip;
mod math_operations;
mod missing_semicolons;
mod smart_variable_naming;
mod symbol_literal_recovery;
mod stack_copy_vec_return;
mod stack_frame;
mod storage_access;
mod undefined_helpers;
mod trailing_unreachable_cleanup;
mod type_tag_guard_cleanup;
mod unreachable_cleanup;
mod variable_naming;
mod vm_scaffold_cleanup;
mod status_result_guard_loop;
mod status_result_guard_label;
mod status_result_guard_text;

pub use consolidate_comments::ConsolidateCommentsPattern;
pub use conversion_elimination::ConversionEliminationPattern;
pub use deduplicate_variables::DeduplicateVariablesPattern;
pub use dead_temp_cleanup::DeadTempCleanupPattern;
pub use guard_early_return::GuardEarlyReturn;
pub use initial_assignment::InitialAssignmentPattern;
pub use inline_val_roundtrip::InlineValRoundtripPattern;
pub use loop_break_tail_return::LoopBreakTailReturn;
pub use loop_if_break_else::LoopIfBreakElse;
pub use loop_no_control::LoopNoControlToBlock;
pub use math_operations::MathOperationsPattern;
pub use missing_semicolons::MissingSemicolonsPattern;
pub use smart_variable_naming::SmartVariableNamingPattern;
pub use symbol_literal_recovery::SymbolLiteralRecoveryPattern;
pub use stack_copy_vec_return::StackCopyVecReturnPattern;
pub use stack_frame::StackFramePattern;
pub use status_result_guard_loop::StatusResultGuardLoopPattern;
pub use status_result_guard_label::StatusResultGuardLabelPattern;
pub use status_result_guard_text::StatusResultGuardTextPattern;
pub use storage_access::StorageAccessPattern;
pub use trailing_unreachable_cleanup::TrailingUnreachableCleanupPattern;
pub use type_tag_guard_cleanup::TypeTagGuardCleanupPattern;
pub use undefined_helpers::UndefinedHelpersPattern;
pub use unreachable_cleanup::UnreachableCleanupPattern;
pub use unwrap_if_else::UnwrapIfElseBlock;
pub use variable_naming::VariableNamingPattern;
pub use vm_scaffold_cleanup::VmScaffoldCleanupPattern;
