[[patterns]]
name = "function_name2({args})"
hash = "unique_hash_if_available"
pattern = """
    var_c = wrap_i32(arg_b) & 255;
    var_d = var_c != 69;
    if var_d {
        var_e = var_c == 11;
        if var_e {
            store_i64(arg_a + 16, arg_b >>s 63);
            store_i64(arg_a + 8, arg_b >>s 0);
        } else {
            store_i64(arg_a + 8, 0);
            var_f = 1;
        }
    } else {
        var_g = int.obj_to_i128_hi64(arg_b);
        var_h = int.obj_to_i128_lo64(arg_b);
        store_i64(arg_a + 16, var_g);
        store_i64(arg_a + 8, var_h);
    }
    if !var_d || var_d && var_e {
        var_f = 0;
    }
    store_i64(arg_a, var_f);
"""
body_replace = """
    let e = Env;
    V::try_from_val(&e, amount)
"""


[[patterns]]
name = "function_name({args})"
hash = "unique_hash_if_available"
pattern = """var_c = 0;
    if arg_b <= 9 {
        var_d = arg_b;
        var_e = arg_a;
        while true {
            if var_d {
                var_c << 0 | 0
            }
            var_f = load_8u_i32(var_e);
            var_g = 1;
            if var_f != 95 {
                if (var_f - 48 & 255) >= 10 {
                    if (var_f - 65 & 255) >= 26 {
                        if (var_f - 97 & 255) > 25 {
                            break;
                        }
                        var_g = var_f - 59;
                    } else {
                        var_g = var_f - 53;
                    }
                } else {
                    var_g = var_f - 46;
                }
            }
            var_c = extend_u_i64(var_g) & 255 | var_c << 0;
            var_d -= 1;
            var_e++;
        }
    }
    var_h = buf.symbol_new_from_linear_memory(extend_u_i64(arg_a) << 32 | 0, extend_u_i64(arg_b) << 32 | 0);
    var_h
"""
body_replace = """
    symbol_new_from_linear_memory
"""
