mod consolidate_comments;
mod conversion_elimination;
mod constant_guard_if;
mod constant_condition_fold;
mod deduplicate_variables;
mod dead_temp_cleanup;
mod dead_let_pure_cleanup;
mod decode_i128_helper_cleanup;
mod extract_call_inline_if_args;
mod extract_assign_mload64_expr;
mod extract_if_mload32_guard;
mod extract_if_inline_cond_expr;
mod extract_if_mload64_expr;
mod extract_inline_mload_val_arg;
mod i32_flag_if_simplify;
mod i32_flag_inline_if_propagate;
mod inline_if_assign_unwrap;
mod inline_val_roundtrip;
mod inline_single_use_alias;
mod inline_generated_single_use_let;
mod inline_status_mload_guard;
mod math_operations;
mod mload_temp_assign_fold;
mod mload_expression_cleanup;
mod missing_semicolons;
mod noop_match_loop;
mod smart_variable_naming;
mod symbol_literal_recovery;
mod serialize_bytes_fix;
mod stack_copy_vec_return;
mod status_guard_block_unwrap;
mod status_if_ne1_to_guard;
mod storage_access;
mod trailing_unreachable_cleanup;
mod type_tag_guard_cleanup;
mod type_tag_guard_strip;
mod unreachable_cleanup;
mod vm_scaffold_cleanup;
mod wasm_type_guard_prune;
mod vec_builder_assignment;
mod status_result_guard_loop;
mod status_result_guard_label;
mod status_result_guard_text;
mod unwrap_try_from_val_if;
mod unwrap_type_tag_ok_if;

pub use consolidate_comments::ConsolidateCommentsPattern;
pub use conversion_elimination::ConversionEliminationPattern;
pub use constant_guard_if::ConstantGuardIfPattern;
pub use constant_condition_fold::ConstantConditionFoldPattern;
pub use deduplicate_variables::DeduplicateVariablesPattern;
pub use dead_temp_cleanup::DeadTempCleanupPattern;
pub use dead_let_pure_cleanup::DeadLetPureCleanupPattern;
pub use decode_i128_helper_cleanup::DecodeI128HelperCleanupPattern;
pub use extract_call_inline_if_args::ExtractCallInlineIfArgsPattern;
pub use extract_assign_mload64_expr::ExtractAssignMload64ExprPattern;
pub use extract_if_inline_cond_expr::ExtractIfInlineCondExprPattern;
pub use extract_if_mload32_guard::ExtractIfMload32GuardPattern;
pub use extract_if_mload64_expr::ExtractIfMload64ExprPattern;
pub use extract_inline_mload_val_arg::ExtractInlineMloadValArgPattern;
pub use i32_flag_if_simplify::I32FlagIfSimplifyPattern;
pub use i32_flag_inline_if_propagate::I32FlagInlineIfPropagatePattern;
pub use inline_if_assign_unwrap::InlineIfAssignUnwrapPattern;
pub use inline_val_roundtrip::InlineValRoundtripPattern;
pub use inline_single_use_alias::InlineSingleUseAliasPattern;
pub use inline_generated_single_use_let::InlineGeneratedSingleUseLetPattern;
pub use inline_status_mload_guard::InlineStatusMloadGuardPattern;
pub use math_operations::MathOperationsPattern;
pub use mload_temp_assign_fold::MloadTempAssignFoldPattern;
pub use mload_expression_cleanup::MloadExpressionCleanupPattern;
pub use missing_semicolons::MissingSemicolonsPattern;
pub use noop_match_loop::NoopMatchLoopPattern;
pub use smart_variable_naming::SmartVariableNamingPattern;
pub use symbol_literal_recovery::SymbolLiteralRecoveryPattern;
pub use serialize_bytes_fix::SerializeBytesFixPattern;
pub use stack_copy_vec_return::StackCopyVecReturnPattern;
pub use status_guard_block_unwrap::StatusGuardBlockUnwrapPattern;
pub use status_if_ne1_to_guard::StatusIfNe1ToGuardPattern;
pub use status_result_guard_loop::StatusResultGuardLoopPattern;
pub use status_result_guard_label::StatusResultGuardLabelPattern;
pub use status_result_guard_text::StatusResultGuardTextPattern;
pub use storage_access::StorageAccessPattern;
pub use trailing_unreachable_cleanup::TrailingUnreachableCleanupPattern;
pub use type_tag_guard_cleanup::TypeTagGuardCleanupPattern;
pub use type_tag_guard_strip::TypeTagGuardStripPattern;
pub use unreachable_cleanup::UnreachableCleanupPattern;
pub use vm_scaffold_cleanup::VmScaffoldCleanupPattern;
pub use wasm_type_guard_prune::WasmTypeGuardPrunePattern;
pub use vec_builder_assignment::VecBuilderAssignmentPattern;
pub use unwrap_try_from_val_if::UnwrapTryFromValIfPattern;
pub use unwrap_type_tag_ok_if::UnwrapTypeTagOkIfPattern;
