mod consolidate_comments;
mod conversion_elimination;
mod constant_guard_if;
mod deduplicate_variables;
mod dead_temp_cleanup;
mod inline_val_roundtrip;
mod math_operations;
mod mload_temp_assign_fold;
mod missing_semicolons;
mod noop_match_loop;
mod smart_variable_naming;
mod symbol_literal_recovery;
mod serialize_bytes_fix;
mod stack_copy_vec_return;
mod status_guard_block_unwrap;
mod storage_access;
mod trailing_unreachable_cleanup;
mod type_tag_guard_cleanup;
mod type_tag_guard_strip;
mod unreachable_cleanup;
mod vm_scaffold_cleanup;
mod wasm_type_guard_prune;
mod vec_builder_assignment;
mod status_result_guard_loop;
mod status_result_guard_label;
mod status_result_guard_text;
mod unwrap_try_from_val_if;
mod unwrap_type_tag_ok_if;

pub use consolidate_comments::ConsolidateCommentsPattern;
pub use conversion_elimination::ConversionEliminationPattern;
pub use constant_guard_if::ConstantGuardIfPattern;
pub use deduplicate_variables::DeduplicateVariablesPattern;
pub use dead_temp_cleanup::DeadTempCleanupPattern;
pub use inline_val_roundtrip::InlineValRoundtripPattern;
pub use math_operations::MathOperationsPattern;
pub use mload_temp_assign_fold::MloadTempAssignFoldPattern;
pub use missing_semicolons::MissingSemicolonsPattern;
pub use noop_match_loop::NoopMatchLoopPattern;
pub use smart_variable_naming::SmartVariableNamingPattern;
pub use symbol_literal_recovery::SymbolLiteralRecoveryPattern;
pub use serialize_bytes_fix::SerializeBytesFixPattern;
pub use stack_copy_vec_return::StackCopyVecReturnPattern;
pub use status_guard_block_unwrap::StatusGuardBlockUnwrapPattern;
pub use status_result_guard_loop::StatusResultGuardLoopPattern;
pub use status_result_guard_label::StatusResultGuardLabelPattern;
pub use status_result_guard_text::StatusResultGuardTextPattern;
pub use storage_access::StorageAccessPattern;
pub use trailing_unreachable_cleanup::TrailingUnreachableCleanupPattern;
pub use type_tag_guard_cleanup::TypeTagGuardCleanupPattern;
pub use type_tag_guard_strip::TypeTagGuardStripPattern;
pub use unreachable_cleanup::UnreachableCleanupPattern;
pub use vm_scaffold_cleanup::VmScaffoldCleanupPattern;
pub use wasm_type_guard_prune::WasmTypeGuardPrunePattern;
pub use vec_builder_assignment::VecBuilderAssignmentPattern;
pub use unwrap_try_from_val_if::UnwrapTryFromValIfPattern;
pub use unwrap_type_tag_ok_if::UnwrapTypeTagOkIfPattern;
