[[patterns]]
name = "try_from_val"
pattern = """
    var_b = global_a - 16;
    var_c = global_a - 16;
    var_d = load_i32(arg_a);
    match var_d - 1 {
        0 => {
            var_e = try_from_val_string(1048729, 7);
            var_f = load_i64(arg_a + 8);
            var_g = try_from_val_i32(var_e, var_f);
            var_h = var_g;
        }
        1 => {
            var_i = try_from_val_string(1048736, 5);
            var_j = load_i64(arg_a + 8);
            var_k = try_from_val_i32(var_i, var_j);
            var_h = var_k;
        }
        2 => {
            var_l = try_from_val_string(1048741, 5);
            store_i64(var_b, var_l);
            var_m = try_from_val_vec_linear(var_b, 1);
            var_h = var_m;
        }
        default => {
            var_n = try_from_val_string(1048720, 9);
            var_o = load_i64(arg_a + 16);
            store_i64(var_b + 8, var_o);
            var_p = load_i64(arg_a + 8);
            store_i64(var_b, var_p);
            var_q = try_from_val_i128(1048664, 2, var_b, 2);
            var_r = try_from_val_i32(var_n, var_q);
            var_h = var_r;
        }
    }
    var_h
"""
body_replace = """
    V::try_from_val(&self.env, &rv).unwrap_optimized()
"""


[[patterns]]
name = "try_from_val_i32"
pattern = """
    var_c = global_a - 16;
    var_d = global_a - 16;
    store_i64(var_c + 8, arg_b);
    store_i64(var_c, arg_a);
    var_e = try_from_val_vec_linear(var_c, 2);
    var_e
"""
body_replace = """
    V::try_from_val(&self.env, &rv).unwrap_optimized()
"""
[[patterns]]
name = "try_from_val_i64"
pattern = """
    if ((arg_c ^ arg_b >> 63) != 0) | (arg_b - -36028797018963968 > 72057594037927935) {
        var_d = int.obj_from_i128_pieces(arg_c, arg_b);
        var_e = var_d;
    } else {
        var_e = arg_b << 0 | 0;
    }
    store_i64(arg_a + 8, var_e);
    store_i64(arg_a, 0);
"""
body_replace = """
    V::try_from_val(&self.env, &rv).unwrap_optimized()
"""


[[patterns]]
name = "try_from_val_i128"
pattern = """
    if arg_b != arg_d {
        panic!("Exit program.");
    }
    var_e = map
        .map_new_from_linear_memory(
            extend_u_i64(arg_a) << 32 | 0,
            extend_u_i64(arg_c) << 32 | 0,
            extend_u_i64(arg_b) << 32 | 0,
        );
    var_e
"""
body_replace = """
    V::try_from_val(&self.env, &rv).unwrap_optimized()
"""

[[patterns]]
name = "try_from_val_u128"
pattern = """
    if arg_c != arg_e {
        panic!("Exit program.");
    }
    map.map_unpack_to_linear_memory(arg_a, extend_u_i64(arg_b) << 32 | 0, extend_u_i64(arg_d) << 32 | 0, extend_u_i64(arg_c) << 32 | 0)
"""
body_replace = """
    V::try_from_val(&self.env, &rv).unwrap_optimized()
"""

[[patterns]]
name = "try_from_val_vec_linear"
pattern = """
    var_c = vec
        .vec_new_from_linear_memory(
            extend_u_i64(arg_a) << 32 | 0,
            extend_u_i64(arg_b) << 32 | 0,
        );
    var_c
"""
body_replace = """
    V::try_from_val(&self.env, &rv).unwrap_optimized()
"""


[[patterns]]
name = "try_from_val_i128_hi_lo"
pattern = """
    var_c = wrap_i32(arg_b) & 255;
    if var_c != 69 {
        if var_c != 11 {
            store_i64(arg_a + 8, Error(Value, UnexpectedType));
            var_d = 1;
        } else {
            store_i64(arg_a + 16, arg_b >> 63);
            store_i64(arg_a + 8, arg_b >> 0);
            var_d = 0;
        }
    } else {
        var_e = int.obj_to_i128_hi64(arg_b);
        var_f = int.obj_to_i128_lo64(arg_b);
        store_i64(arg_a + 16, var_e);
        store_i64(arg_a + 8, var_f);
        var_d = 0;
    }
    store_i64(arg_a, var_d);

"""
body_replace = """
    V::try_from_val(&self.env, &rv).unwrap_optimized()
"""

[[patterns]]
name = "try_from_val_string"
pattern = """
    var_c = 0;
    if arg_b <= 9 {
        var_d = arg_b;
        var_e = arg_a;
        while true {
            if var_d {
                var_c << 0 | Symbol()
            }
            var_f = load_8u_i32(var_e);
            var_g = 1;
            if var_f != 95 {
                if (var_f - 48 & 255) >= 10 {
                    if (var_f - 65 & 255) >= 26 {
                        if (var_f - 97 & 255) > 25 {
                            break;
                        }
                        var_g = var_f - 59;
                    } else {
                        var_g = var_f - 53;
                    }
                } else {
                    var_g = var_f - 46;
                }
            }
            var_c = extend_u_i64(var_g) & 255 | var_c << 0;
            var_d -= 1;
            var_e++;
        }
    }
    var_h = buf.symbol_new_from_linear_memory(extend_u_i64(arg_a) << 32 | 0, extend_u_i64(arg_b) << 32 | 0);
    var_h
"""
body_replace = """
    V::try_from_val(&self.env, &rv).unwrap_optimized()
"""


[[patterns]]
name = "write_allowance"
pattern = """
    var_f = global_a - 80;
    var_g = global_a - 80;
    var_h = arg_d == 0 ? arg_c != 0 : arg_d > 0;
    if var_h != 0 {
        var_i = func_29();
        if var_i > arg_e {
            panic!("Exit program.");
        }
    }
    store_i64(var_f + 32, arg_b);
    store_i64(var_f + 24, arg_a);
    store_i64(var_f + 16, 0);
    store_i64(var_f + 56, arg_b);
    store_i64(var_f + 48, arg_a);
    store_i64(var_f + 40, 0);
    var_j = try_from_val(var_f + 40);
    try_from_val_i64(var_f, arg_c, arg_d)
    store_i64(var_f + 72, extend_u_i64(arg_e) << 32 | 0);
    var_k = load_i64(var_f + 8);
    store_i64(var_f + 64, var_k);
    var_l = try_from_val_i128(1048704, 2, var_f - -64, 2);
    ledger.put_contract_data(var_j, var_l, 0)
    if var_h {
        var_m = func_29();
        if var_m > arg_e {
            panic!("Exit program.");
        }
        arg_e -= var_m;
        extend_ttl(var_f + 16, 0, arg_e, arg_e)
    }
"""
body_replace = """
    let allowance = AllowanceValue {
        amount,
        expiration_ledger,
    };

    if amount > 0 && expiration_ledger < e.ledger().sequence() {
        panic!("expiration_ledger is less than ledger seq when amount > 0")
    }

    let key = DataKey::Allowance(AllowanceDataKey { from, spender });
    e.storage().temporary().set(&key.clone(), &allowance);

    if amount > 0 {
        let live_for = expiration_ledger
            .checked_sub(e.ledger().sequence())
            .unwrap();

        e.storage().temporary().extend_ttl(&key, live_for, live_for)
    }
"""

[[patterns]]
name = "extend_ttl"
pattern = """
    var_e = try_from_val(arg_a);
    ledger
        .extend_contract_data_ttl(
            var_e,
            arg_b,
            extend_u_i64(arg_c) << 32 | 0,
            extend_u_i64(arg_d) << 32 | 0,
        )
"""
body_replace = """
    let e = &env;    
    e.storage()
        .instance()
        .extend_ttl(INSTANCE_LIFETIME_THRESHOLD, INSTANCE_BUMP_AMOUNT);
"""

[[patterns]]
name = "extend_ttl"
pattern = """
    ledger
    .extend_current_contract_instance_and_code_ttl(
        INSTANCE_LIFETIME_THRESHOLD,
        120960,
    )
"""
body_replace = """
let e = &env;    
e.storage()
    .instance()
    .extend_ttl(INSTANCE_LIFETIME_THRESHOLD, INSTANCE_BUMP_AMOUNT);
"""


[[patterns]]
name = "read_allowance"
pattern = """
    var_d = 0;
    var_e = global_a - 64;
    var_f = global_a - 64;
    store_i64(var_e + 16, arg_c);
    store_i64(var_e + 8, arg_b);
    arg_c = 0;
    store_i64(var_e, 0);
    var_g = try_from_val(var_e);
    var_h = has_internal(var_g, 0);
    if var_h == 0 {
        arg_b = 0;
    } else {
        var_i = ledger.get_contract_data(var_g, 0);
        for ; var_d == 16; var_e = var_d + 8 {
            store_i64(var_e + 24 + var_d, 0);
        }
        var_j = (var_i & 255) != Map(obj#0);
        if !var_j {
            try_from_val(var_i, 1048704, 2, var_e + 24, 2)
            var_k = load_i64(var_e + 24);
            try_from_val(var_e + 40, var_k)
            var_l = load_i64(var_e + 40);
            var_m = var_l == 0 == 0;
            if !var_m {
                var_n = load_i64(var_e + 32);
            }
        }
        if var_j || var_m || !var_j && (var_n & 255) != 0 {
            panic!("Exit program.");
        }
        var_o = load_i64(var_e + 48);
        var_p = load_i64(var_e + 56);
        var_q = func_29();
        var_d = wrap_i32(var_n >> 32);
        var_r = var_q > var_d;
        arg_b = var_r ? 0 : var_p;
        var_s = var_q > var_d;
        arg_c = var_s ? 0 : var_o;
    }
    store_i64(arg_a + 8, arg_b);
    store_i64(arg_a, arg_c);
    store_i32(arg_a + 16, var_d);
"""
body_replace = """
    let e = &env;
    let key = DataKey::Allowance(AllowanceDataKey { from, spender });
    if let Some(allowance) = e.storage().temporary().get::<_, AllowanceValue>(&key) {
        if allowance.expiration_ledger < e.ledger().sequence() {
            AllowanceValue {
                amount: 0,
                expiration_ledger: allowance.expiration_ledger,
            }
        } else {
            allowance
        }
    } else {
        AllowanceValue {
            amount: 0,
            expiration_ledger: 0,
        }
    }
"""

[[patterns]]
name = "spend_balance"
pattern = """
    var_d = global_a - 16;
    var_e = global_a - 16;
    read_balance(var_d, arg_a)
    var_f = load_i64(var_d);
    var_g = var_f < arg_b;
    var_h = load_i64(var_d + 8);
    if (arg_c == var_h ? var_g : var_h < arg_c) == 0 {
        panic!("Exit program.");
    }
    var_i = arg_c;
    var_j = var_f < arg_b;
    arg_c = var_h - arg_c - extend_u_i64(var_j);
    if ((var_i ^ var_h) & (var_h ^ arg_c)) >= 0 {
        panic!("Exit program.");
    }
    func_34(arg_a, var_f - arg_b, arg_c)
"""
body_replace = """
    let e = &env;
    let balance = read_balance(e, addr.clone());
    if balance < amount {
        panic!("insufficient balance");
    }
    write_balance(e, addr, balance - amount);
"""


[[patterns]]
name = "write_balance"
pattern = """
    var_d = global_a - 48;
    var_e = global_a - 48;
    store_i64(var_d + 24, 1);
    store_i64(var_d + 32, arg_a);
    var_f = func_17(var_d + 24);
    try_from_val(var_d + 8, arg_b, arg_c)
    var_g = load_i64(var_d + 16);
    ledger.put_contract_data(var_f, var_g, 1)
    func_15(var_d + 24)
"""
body_replace = """
    let e = &env;
    let key = DataKey::Balance(addr);
    e.storage().persistent().set(&key, &amount);
    e.storage()
        .persistent()
        .extend_ttl(&key, BALANCE_LIFETIME_THRESHOLD, BALANCE_BUMP_AMOUNT);
"""

[[patterns]]
name = "spend_allowance"
pattern = """
    var_e = global_a - 32;
    var_f = global_a - 32;
    read_allowance(var_e + 8, arg_a, arg_b)
    var_g = load_i64(var_e + 8);
    var_h = var_g < arg_c;
    var_i = load_i64(var_e + 16);
    if (arg_d == var_i ? var_h : var_i < arg_d) == 0 {
        if arg_d == 0 ? arg_c != 0 : arg_d > 0 {
            var_j = var_g < arg_c;
            var_k = load_i32(var_e + 24);
            write_allowance(arg_a, arg_b, var_g - arg_c, var_i - arg_d - extend_u_i64(var_j), var_k)
        }
    }
    panic!("Exit program.");

"""
body_replace = """
    let e = &env;
    let allowance = AllowanceValue {
        amount,
        expiration_ledger,
    };

    if amount > 0 && expiration_ledger < e.ledger().sequence() {
        panic!("expiration_ledger is less than ledger seq when amount > 0")
    }

    let key = DataKey::Allowance(AllowanceDataKey { from, spender });
    e.storage().temporary().set(&key.clone(), &allowance);

    if amount > 0 {
        let live_for = expiration_ledger
            .checked_sub(e.ledger().sequence())
            .unwrap();

        e.storage().temporary().extend_ttl(&key, live_for, live_for)
    }
"""
[[patterns]]
name = "read_balance"
pattern = """
    var_c = 0;
    var_d = global_a - 48;
    var_e = global_a - 48;
    store_i64(var_d, 1);
    store_i64(var_d + 8, arg_b);
    arg_b = 0;
    var_f = try_from_val(var_d);
    var_g = has_internal(var_f, 1);
    if var_g {
        var_h = ledger.get_contract_data(var_f, 1);
        try_from_val_i128_hi_lo(var_d + 24, var_h)
        var_i = load_i64(var_d + 24);
        if var_i == 0 == 0 {
            panic!("Exit program.");
        }
        var_j = load_i64(var_d + 40);
        var_c = var_j;
        var_k = load_i64(var_d + 32);
        arg_b = var_k;
        func_15(var_d)
    }
    store_i64(arg_a + 8, var_c);
    store_i64(arg_a, arg_b);
"""
body_replace = """
    let key = DataKey::Balance(addr);
    let e = &env;
    if let Some(balance) = e.storage().persistent().get::<DataKey, i128>(&key) {
        e.storage()
            .persistent()
            .extend_ttl(&key, BALANCE_LIFETIME_THRESHOLD, BALANCE_BUMP_AMOUNT);
        balance
    } else {
        0
    }
"""

[[patterns]]
name = "receive_balance"
pattern = """
    var_d = global_a - 16;
    var_e = global_a - 16;
    read_balance(var_d, arg_a)
    var_f = load_i64(var_d + 8);
    var_g = arg_c;
    var_h = load_i64(var_d);
    arg_b += var_h;
    arg_c = extend_u_i64(arg_b < var_h) + arg_c + var_f;
    if ((var_f var_g -1) & (var_f arg_c)) >= 0 {
        write_balance(arg_a, arg_b, arg_c)
    }
    panic!("Exit program.");
"""
body_replace = """
    let e = &env;
    let balance = read_balance(e, addr.clone());
    write_balance(e, addr, balance + amount);
"""

[[patterns]]
name = "hello"
pattern = """
    var_b = global_a - 48;
    var_c = global_a - 48;
    store_i64(var_b + 16, to);
    var_d = load_i64(var_b + 16);
    store_i64(var_b + 8, var_d);
    var_e = wrap_i32(var_d) & 255;
    store_i64(var_b, extend_u_i64(var_e != 74 & var_e != 14));
    var_f = load_i64(var_b);
    if wrap_i32(var_f) == 0 {
        var_g = load_i64(var_b + 8);
        store_i64(var_b + 32, var_g);
        store_i64(var_b + 24, Hello);
        var_h = vec.vec_new_from_linear_memory(extend_u_i64(var_b + 24) 32 0, 2);
        var_h
    }
    panic!("Exit program.");
"""
body_replace = """
    !vec[(symbol_short!(to), from)]
"""

[[patterns]]
name = "symbol_short"
pattern = """
    var_c = 0;
    var_d = global_a - 32;
    var_e = global_a - 32;
    store_i64(var_d + 8, arg_b);
    store_i64(var_d, arg_a);
    for ; var_c != 16; var_c += 8 {
        store_i64(var_d + 16 + var_c, 0);
    }
    for var_c = 0; var_c == 16; var_c += 8 {
        var_f = load_i64(var_c + var_d);
        store_i64(var_d + 16 + var_c, var_f);
    }
    try_from_val_vec_linear(var_d + 16, 2)
    0
"""
body_replace = """
    (symbol_short!("burn"), from)
"""

[[patterns]]
name = "symbol_short"
pattern = """
    var_b = global_a - 48;
    var_c = global_a - 48;
    var_d = load_i64(arg_a + 16);
    store_i64(var_b + 16, var_d);
    var_e = load_i64(arg_a + 8);
    store_i64(var_b + 8, var_e);
    var_f = load_i64(arg_a);
    store_i64(var_b, var_f);
    for arg_a = 0; arg_a != 24; arg_a += 8 {
        store_i64(var_b + 24 + arg_a, 0);
    }
    for arg_a = 0; arg_a == 24; arg_a += 8 {
        var_g = load_i64(arg_a + var_b);
        store_i64(var_b + 24 + arg_a, var_g);
    }
    try_from_val_vec_linear(var_b + 24, 3)
    0
"""
body_replace = """
    (symbol_short!("transfer"), from, to)
"""

[[patterns]]
name = "publish_transfer"
pattern = """
    var_e = global_a - 48;
    var_f = global_a - 48;
    store_i64(var_e + 40, arg_b);
    store_i64(var_e + 32, arg_a);
    store_i64(var_e + 24, transfer);
    var_g = func_41(var_e + 24);
    try_from_val_i64(var_e + 8, arg_c, arg_d)
    var_h = load_i64(var_e + 16);
    context.contract_event(var_g, var_h)
"""
body_replace = """
    let topics = (symbol_short!("event"), from, amount);
    env.events().publish(topics, amount);
"""

[[patterns]]
name = "publish_burn"
pattern = """
    var_d = global_a - 16;
    var_e = global_a - 16;
    var_f = symbol_short(burn, arg_a);
    func_31(var_d, arg_b, arg_c)
    var_g = load_i64(var_d + 8);
    context.contract_event(var_f, var_g)
"""
body_replace = """
    let topics = (symbol_short!("burn"), from);
    env.events().publish(topics, amount);
"""

[[patterns]]
name = "has_internal"
pattern = """
    var_c = ledger.has_contract_data(arg_a, arg_b);
    var_c == 1
"""
body_replace = """
    env.storage().instance().has_contract_data(&self.env, key, storage_type)
        .unwrap_infallible()
        .into()
"""
[[patterns]]
name = "get_metadata"
pattern = """var_b = 0;
    var_c = global_a - 32;
    var_d = global_a - 32;
    var_e = has_internal(METADATA, 0);
    if var_e {
        var_f = ledger.get_contract_data(METADATA, 0);
        for ; var_b == 24; var_c = var_b + 8 {
            store_i64(var_c + 8 + var_b, 0);
        }
        var_g = (var_f & 255) != Map(obj#0);
        if !var_g {
            try_from_val(var_f, 1048816, 3, var_c + 8, 3)
            var_h = load_i64(var_c + 8);
            var_i = (var_h & 255) != 0;
            if !var_i {
                var_j = load_i64(var_c + 16);
                var_k = (var_j & 255) != String(obj#0);
                if !var_k {
                    var_l = load_i64(var_c + 24);
                }
            }
        }
        if var_g || var_i || !var_g && var_k || !var_g && !var_i && (var_l & 255) != String(obj#0) {
            panic!("Exit program.");
        }
        store32_i32(arg_a + 24, var_h >> 32);
        store_i64(arg_a + 16, var_l);
        store_i64(arg_a + 8, var_j);
        var_m = 1;
    } else {
        var_m = 0;
    }
    store_i64(arg_a, var_m);
"""
body_replace = """
    self.env
    .storage()
    .instance()
    .get(&METADATA_KEY)
    .unwrap_optimized()
"""


[[patterns]]
name = "read_decimals"
pattern = """
    var_a = global_a - 32;
    var_b = global_a - 32;
    get_metadata(var_a)
    var_c = load_i64(var_a);
    if var_c == 0 {
        panic!("Exit program.");
    }
    var_d = load_32u_i64(var_a + 24);
    var_d << 32 | 0
"""
body_replace = """
    let util = TokenUtils::new(e);
    util.metadata().get_metadata().decimals
"""

[[patterns]]
name = "read_symbol"
pattern = """
    var_a = global_a - 32;
    var_b = global_a - 32;
    get_metadata(var_a)
    var_c = load_i64(var_a);
    if var_c == 0 {
        panic!("Exit program.");
    }
    var_d = load_i64(var_a + 16);
    var_d
"""
body_replace = """
    let util = TokenUtils::new(e);
    util.metadata().get_metadata().symbol
"""

